version: '3'
services:
  db_inclua:
    image: postgres:12.0-alpine
    container_name: postgresql-inclua
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5438:5432
  app_inclua:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    depends_on:
      - db_inclua
    links:
      - db_inclua
