version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=lara
      - MYSQL_USER=raphael
      - MYSQL_PASSWORD=secret
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"